# Generated by Django 4.2.2 on 2023-06-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_Name', models.CharField(max_length=50)),
                ('Author_Sure_Name', models.CharField(max_length=50)),
                ('Author_Age', models.PositiveIntegerField()),
                ('Info', models.TextField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.categorys')),
            ],
        ),
    ]
