# Generated by Django 4.2.2 on 2023-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
